# .github/workflows/douban.yml
name: douban
on:
  workflow_dispatch: 
  schedule:
  - cron: "0 0,0,12,23 * * *"
  watch:
    types: [started]
    
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: delete old file
      run: |
        rm -rf ./data
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 169652231
        type: movie
        format: csv
        dir: ./data/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: 169652231
        type: book
        format: csv
        dir: ./data/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './data/douban'
